import { lazy } from "react";
import type { ToolMeta } from "../tool-meta";

export const JSON_FORMATTER_META: ToolMeta = {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, query, filter, repair, and inspect JSON in real time with non-blocking Web Worker performance. 100% client-side.',
    category: 'json-tools',
    tag: 'JSON',
    toolComponent: lazy(() => import('../../components/tools/json-tools/JsonFormatter')),
    keywords: [
        'json formatter',
        'json validator',
        'json beautifier',
        'format json online',
        'json pretty print',
        'minify json',
        'json syntax checker',
        'json viewer',
        'json lint',
        'beautify json',
        'json filter',
        'jsonpath query',
        'json tree viewer',
        'json auto repair',
        'large json formatter',
    ],
    about: {
        summary:
            'JSON Formatter & Validator instantly formats raw or minified JSON into clean, readable output with proper indentation. Powered by an asynchronous non-blocking engine, it supports massive JSON payloads, JSONPath & JS expression filtering, interactive collapsible Tree & Table visualizers, 1-click Auto-Repair for broken JSON, key case conversions, and TypeScript interface exports. Everything runs in your browser, no data is sent anywhere.',
        useCases: [
            'Formatting minified API responses into readable, indented JSON',
            'Filtering large JSON responses with JSONPath, dot notation, or JS expressions',
            'Fixing relaxed or broken JSON (unquoted keys, single quotes, trailing commas, Python literals)',
            'Inspecting deep JSON hierarchies with an interactive Tree Explorer and Table Grid',
            'Validating JSON payloads with pinpoint line & column syntax error diagnostics',
            'Generating TypeScript interfaces and type definitions directly from JSON',
            'Minifying JSON payloads to reduce bandwidth and payload size for production',
        ],
        features: [
            'Non-blocking background processing supporting large multi-megabyte JSON files',
            'Format with 2 spaces, 4 spaces, 3 spaces, or Tab indentation, plus minification',
            'Pinpoint syntax error locator with visual indicator and 1-click Auto-Repair',
            'JSONPath, dot notation, and JavaScript expression query filter engine',
            'Interactive Collapsible Tree Explorer with type highlighting and quick JSONPath copy',
            'Searchable and sortable Table Grid view for JSON arrays with instant CSV export',
            'Deep structural metrics: key counts, nesting depth, type breakdown, and compression analysis',
            'Key sorting (A-Z, Z-A, Natural, Length) and recursive key case conversions',
            'Export to TypeScript interfaces, YAML, or downloadable JSON file',
            '100% Client-Side execution — zero data sent to external servers',
        ],
        tip: 'Need to extract specific data from a nested API response? Use the Query bar with dot notation like "data.products[*].name" or a JavaScript expression like "x => x.price > 100" to filter instantly.',
    },
    addedAt: '2026-03-10',
    complexity: 'moderate',
    featured: true,
    isNew: true,
    status: 'beta',
    seo: {
        description: 'Instantly format, validate, filter, repair, and minify JSON in your browser with non-blocking Web Worker performance. Features interactive Tree & Table views, JSONPath queries, and TypeScript export.',
        extraKeywords: [
            'json formatter online',
            'json validator online',
            'json beautifier online',
            'format json free',
            'json pretty print online',
            'minify json online',
            'json syntax checker online',
            'json viewer online',
            'json lint online',
            'jsonpath filter online',
            'large json formatter',
        ],
        title: 'JSON Formatter & Validator — ToolBox4Devs',
    }
}
