import { lazy } from 'react'
import type { ToolMeta } from '../tool-meta'

export const PASSWORD_STRENGTH_ANALYZER_META: ToolMeta = {
  slug: 'password-strength-analyzer',
  name: 'Password Strength Analyzer',
  description: 'Analyze password entropy, estimate crack times, detect common patterns, and get actionable improvement tips — all in your browser.',
  category: 'analyze-tools',
  tag: 'analyze',
  keywords: [
    'password strength analyzer',
    'password entropy calculator',
    'crack time estimator',
    'password checker',
    'password security',
    'password audit',
  ],
  toolComponent: lazy(() => import('../../components/tools/analyze-tools/PasswordStrengthAnalyzer')),
  about: {
    summary:
      'Password Strength Analyzer evaluates the security of any password by calculating information entropy (in bits), estimating crack times across online, offline, and GPU-accelerated attack scenarios, detecting common patterns and sequential characters, and providing actionable improvement suggestions. Everything runs locally in your browser — no password is ever transmitted.',
    useCases: [
      'Auditing password strength before deploying a new application',
      'Teaching users about password security and entropy',
      'Evaluating passwords generated by password managers',
      'Testing password policies and complexity requirements',
      'Demonstrating the impact of character diversity on security',
    ],
    features: [
      'Information entropy calculation in bits using character pool analysis',
      'Crack time estimates for online (~100/s), offline (~100K/s), and GPU (~10B/s) attacks',
      'Common password pattern detection (dictionary words, sequences, repetitions)',
      'Character set breakdown (lowercase, uppercase, digits, special characters)',
      'Visual strength meter with score out of 100',
      'Actionable improvement suggestions based on detected weaknesses',
      'Copyable analysis report for documentation and compliance',
    ],
    tip: 'A strong password uses 12+ characters with a mix of uppercase, lowercase, numbers, and special characters — and avoids common dictionary words or patterns like "Password1!"',
  },
  addedAt: '2026-08-23',
  complexity: 'moderate',
  featured: false,
  isNew: true,
  status: 'stable',
  seo: {
    title: 'Password Strength Analyzer — Check Entropy & Crack Time Online',
    description: 'Analyze password strength with entropy calculation, crack time estimates, and pattern detection. Free, runs entirely in your browser.',
    extraKeywords: [
      'password strength checker',
      'password entropy calculator',
      'how strong is my password',
      'password crack time',
      'password security audit',
      'password strength test',
      'entropy bits password',
      'password analyzer online',
      'password strength tool',
      'free password analyzer',
    ],
  },
}
