import { lazy } from "react"
import type { ToolMeta } from "../tool-meta"

export const SQL_FORMATTER_META: ToolMeta = {
  slug: 'sql-formatter',
  name: 'SQL Formatter & Prettifier',
  description: 'Format, indent, validate, and minify SQL queries online. Capitalize keywords, format clauses, and clean up raw database queries.',
  category: 'data-tools',
  tag: 'SQL',
  toolComponent: lazy(() => import('../../components/tools/data-tools/SqlFormatter')),
  keywords: [
    'sql formatter',
    'sql prettifier',
    'sql beautifier',
    'format sql online',
    'minify sql',
    'uppercase sql keywords',
    'sql query cleanup',
    'sql syntax formatter',
  ],
  about: {
    summary:
      'SQL Formatter & Prettifier reorganizes messy, single-line, or minified SQL statements into structured, easy-to-read database queries. It supports automatic keyword uppercase transformations (SELECT, FROM, WHERE, JOIN), custom indentation spacing, and single-line query minification.',
    useCases: [
      'Beautifying raw SQL logged by ORMs (Prisma, Drizzle, Hibernate, Sequelize)',
      'Formatting complex JOINs, subqueries, and window functions for code reviews',
      'Minifying SQL queries to embed in configuration files or code strings',
      'Standardizing SQL style guidelines across a development team',
    ],
    features: [
      'Uppercase SQL keywords option for SELECT, FROM, JOIN, WHERE, HAVING, etc.',
      'Configurable indent sizes (2 spaces or 4 spaces)',
      'Instant minification mode to compress queries into one line',
      'Real-time processing with zero latency and no server uploads',
      'Works with MySQL, PostgreSQL, SQLite, MS SQL Server, and Oracle queries',
    ],
    tip: 'Paste raw SQL generated by your backend ORM query logger to inspect joins and conditions clearly!',
  },
  addedAt: '2026-07-26',
  complexity: 'simple',
  featured: true,
  isNew: true,
  status: 'stable',
  seo: {
    description: 'Format, beautify, and minify SQL queries online. Uppercase keywords, format JOINs and subqueries with custom indentation. Free, 100% browser-based.',
    extraKeywords: [
      'sql formatter free',
      'sql prettifier online',
      'format sql query online',
      'beautify sql online',
      'minify sql online',
    ],
    title: 'SQL Formatter & Prettifier — ToolBox4Devs',
  }
}
