import { useMemo, useState } from 'react'
import { CheckSquare, FileCode2, RotateCcw, Search, Square } from 'lucide-react'
import SectionPanel from '../../ui/SectionPanel'
import OutputPanel from '../../ui/OutputPanel'
import StatCard from '../../ui/StatCard'

type Template = {
  id: string
  name: string
  group: 'Languages & runtimes' | 'Frameworks & tools' | 'Editors & operating systems'
  patterns: string[]
}

const TEMPLATES: Template[] = [
  { id: 'node', name: 'Node.js', group: 'Languages & runtimes', patterns: ['node_modules/', 'npm-debug.log*', 'yarn-debug.log*', 'yarn-error.log*', 'pnpm-debug.log*', '.npm/', '.yarn/cache/', '.pnp.*'] },
  { id: 'python', name: 'Python', group: 'Languages & runtimes', patterns: ['__pycache__/', '*.py[cod]', '*$py.class', '.Python', '.venv/', 'venv/', 'env/', '.pytest_cache/', '.mypy_cache/', '.coverage', 'htmlcov/'] },
  { id: 'java', name: 'Java / JVM', group: 'Languages & runtimes', patterns: ['*.class', '*.jar', '*.war', '*.ear', 'target/', '.gradle/', 'build/'] },
  { id: 'dotnet', name: '.NET', group: 'Languages & runtimes', patterns: ['[Bb]in/', '[Oo]bj/', '*.user', '*.suo', '*.userosscache', '*.sln.docstates'] },
  { id: 'go', name: 'Go', group: 'Languages & runtimes', patterns: ['*.exe', '*.exe~', '*.dll', '*.so', '*.dylib', '*.test', '*.out', 'vendor/'] },
  { id: 'rust', name: 'Rust', group: 'Languages & runtimes', patterns: ['target/', 'Cargo.lock'] },
  { id: 'react', name: 'React / Vite', group: 'Frameworks & tools', patterns: ['dist/', '.vite/', '*.local'] },
  { id: 'next', name: 'Next.js', group: 'Frameworks & tools', patterns: ['.next/', 'out/', '.vercel/'] },
  { id: 'angular', name: 'Angular', group: 'Frameworks & tools', patterns: ['.angular/', 'dist/', 'coverage/'] },
  { id: 'vue', name: 'Vue', group: 'Frameworks & tools', patterns: ['dist/', '.vite/', '*.local'] },
  { id: 'docker', name: 'Docker', group: 'Frameworks & tools', patterns: ['.dockerignore.local', 'docker-compose.override.yml'] },
  { id: 'terraform', name: 'Terraform', group: 'Frameworks & tools', patterns: ['.terraform/', '*.tfstate', '*.tfstate.*', 'crash.log', '*.tfvars', '*.tfvars.json'] },
  { id: 'vscode', name: 'Visual Studio Code', group: 'Editors & operating systems', patterns: ['.vscode/*', '!.vscode/extensions.json', '!.vscode/settings.json', '!.vscode/tasks.json', '!.vscode/launch.json'] },
  { id: 'jetbrains', name: 'JetBrains IDEs', group: 'Editors & operating systems', patterns: ['.idea/', '*.iws', '*.iml', '*.ipr'] },
  { id: 'macos', name: 'macOS', group: 'Editors & operating systems', patterns: ['.DS_Store', '.AppleDouble', '.LSOverride'] },
  { id: 'windows', name: 'Windows', group: 'Editors & operating systems', patterns: ['Thumbs.db', 'Thumbs.db:encryptable', 'ehthumbs.db', 'Desktop.ini', '$RECYCLE.BIN/'] },
]

const DEFAULT_SELECTION = ['node', 'react', 'vscode', 'macos']
const STANDARD_PATTERNS = ['.env', '.env.*', '!.env.example', '*.log', 'coverage/', '.cache/']

export default function GitignoreGenerator() {
  const [selected, setSelected] = useState<string[]>(DEFAULT_SELECTION)
  const [customPatterns, setCustomPatterns] = useState('')
  const [includeStandardPatterns, setIncludeStandardPatterns] = useState(true)
  const [includeComments, setIncludeComments] = useState(true)
  const [query, setQuery] = useState('')

  const filteredTemplates = useMemo(() => {
    const normalized = query.trim().toLowerCase()
    return normalized ? TEMPLATES.filter(template => template.name.toLowerCase().includes(normalized)) : TEMPLATES
  }, [query])

  const output = useMemo(() => {
    const selectedTemplates = TEMPLATES.filter(template => selected.includes(template.id))
    const custom = customPatterns.split(/\r?\n/).map(pattern => pattern.trim()).filter(Boolean)
    const lines: string[] = []
    const seen = new Set<string>()
    const addPattern = (pattern: string) => {
      if (!seen.has(pattern)) {
        seen.add(pattern)
        lines.push(pattern)
      }
    }

    if (includeComments) {
      lines.push('# Generated by ToolBox4Devs — review before committing')
      lines.push('# https://toolbox4devs.com/gitignore-generator')
    }
    if (includeStandardPatterns) {
      if (lines.length) lines.push('')
      if (includeComments) lines.push('# Environment, logs, and generated reports')
      STANDARD_PATTERNS.forEach(addPattern)
    }
    selectedTemplates.forEach(template => {
      if (lines.length) lines.push('')
      if (includeComments) lines.push(`# ${template.name}`)
      template.patterns.forEach(addPattern)
    })
    if (custom.length) {
      if (lines.length) lines.push('')
      if (includeComments) lines.push('# Custom rules')
      custom.forEach(addPattern)
    }
    return lines.join('\n').trim()
  }, [customPatterns, includeComments, includeStandardPatterns, selected])

  const toggleTemplate = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  const reset = () => {
    setSelected(DEFAULT_SELECTION)
    setCustomPatterns('')
    setIncludeStandardPatterns(true)
    setIncludeComments(true)
    setQuery('')
  }
  const patternCount = output.split('\n').filter(line => line && !line.startsWith('#')).length
  const customCount = customPatterns.split(/\r?\n/).filter(pattern => pattern.trim()).length

  return (
    <div className="space-y-6">
      <SectionPanel label="Select project templates" dot="bg-emerald-400" extra={<div className="flex items-center gap-2"><button type="button" onClick={() => setSelected(TEMPLATES.map(template => template.id))} className="text-xs text-accent hover:text-bright transition-colors">All</button><button type="button" onClick={() => setSelected([])} className="text-xs text-dim hover:text-bright transition-colors">Clear</button></div>}>
        <div className="relative mb-4"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-subtle" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Filter templates…" className="input-base w-full pl-9" aria-label="Filter .gitignore templates" /></div>
        {(['Languages & runtimes', 'Frameworks & tools', 'Editors & operating systems'] as const).map(group => {
          const templates = filteredTemplates.filter(template => template.group === group)
          if (!templates.length) return null
          return <fieldset key={group} className="mb-5 last:mb-0"><legend className="mb-2 text-xs font-mono uppercase tracking-wider text-subtle">{group}</legend><div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">{templates.map(template => {
            const isSelected = selected.includes(template.id)
            return <label key={template.id} className={`flex cursor-pointer items-center gap-2 rounded border px-3 py-2 text-sm transition-colors ${isSelected ? 'border-accent/60 bg-accent/10 text-bright' : 'border-border bg-muted/20 text-dim hover:border-border/80 hover:text-main'}`}><input className="sr-only" type="checkbox" checked={isSelected} onChange={() => toggleTemplate(template.id)} />{isSelected ? <CheckSquare size={16} className="shrink-0 text-accent" /> : <Square size={16} className="shrink-0" />}{template.name}</label>
          })}</div></fieldset>
        })}
      </SectionPanel>

      <SectionPanel label="Options" dot="bg-indigo-400">
        <div className="grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer items-center gap-2 text-sm text-main"><input type="checkbox" checked={includeStandardPatterns} onChange={event => setIncludeStandardPatterns(event.target.checked)} className="rounded border-border" />Include common environment and log rules</label><label className="flex cursor-pointer items-center gap-2 text-sm text-main"><input type="checkbox" checked={includeComments} onChange={event => setIncludeComments(event.target.checked)} className="rounded border-border" />Add readable section comments</label></div>
        <label className="mt-4 block text-xs font-medium text-subtle">Custom patterns <span className="font-normal">(one per line)</span><textarea value={customPatterns} onChange={event => setCustomPatterns(event.target.value)} placeholder={'private-notes/\n*.local.json'} rows={4} className="input-base mt-1.5 w-full resize-y font-mono text-sm" /></label>
        <button type="button" onClick={reset} className="mt-4 inline-flex items-center gap-1.5 text-sm text-dim hover:text-bright transition-colors"><RotateCcw size={14} /> Reset defaults</button>
      </SectionPanel>

      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><StatCard label="Templates" value={selected.length} /><StatCard label="Ignore rules" value={patternCount} /><StatCard label="Custom rules" value={customCount} /></div>
      <OutputPanel label="Generated .gitignore" content={output} placeholder="Select one or more templates to generate your .gitignore file." language="text" heightClass="min-h-[320px] max-h-[560px]" />
      <div className="flex items-start gap-2 rounded-lg border border-border bg-muted/30 p-3 text-xs text-dim"><FileCode2 size={16} className="mt-0.5 shrink-0 text-accent" /><p>Review generated rules before committing. A <code className="text-main">.gitignore</code> affects only untracked files; use <code className="text-main">git rm --cached &lt;file&gt;</code> to stop tracking a file already in Git.</p></div>
    </div>
  )
}
